import type { Metadata } from "next";
import { neueRegrade, regonia } from "./_components/fonts/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${neueRegrade.variable} ${regonia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
